server:
  port: 13101

spring:
  application:
    name: account
    index: 0

# Discovery Server Access
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/






